// Auto-generated by Blazing CMS — do not edit

export interface ArrayEntry {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface BooleanEntry {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: boolean;
}

export interface Component {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface DateEntry {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface DynamicZone {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Group {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface MediaTest {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface NumberEntry {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: number;
}

export interface Posts {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  published: boolean;
  publishedAt: string;
  category: string;
  author: string;
}

export interface Relation {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Repeater {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface RichText {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface Select {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface TextEntry {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  field: string;
}

export interface BooleanEntry {
  field: boolean;
}

export interface Checkbox {
  field: boolean;
}

export interface Code {
  field: string;
}

export interface Color {
  field: string;
}

export interface DateEntry {
  field: string;
}

export interface Datetime {
  field: string;
}

export interface Email {
  field: string;
}

export interface Homepage {
  heroTitle: string;
  heroSubtitle: string;
  showFeaturedPosts: boolean;
  featuredPost: string;
}

export interface Json {
  field: unknown;
}

export interface Markdown {
  field: string;
}

export interface MediaSettings {
  field: string;
}

export interface MultiSelect {
  field: string[];
}

export interface NumberEntry {
  field: number;
}

export interface Password {
  field: string;
}

export interface Radio {
  field: string;
}

export interface RichText {
  field: string;
}

export interface Select {
  field: string;
}

export interface SiteSettings {
  siteName: string;
  tagline: string;
  description: string;
  logo: string;
  primaryColor: string;
  secondaryColor: string;
  enableComments: boolean;
}

export interface Slug {
  field: string;
}

export interface TextEntry {
  field: string;
}

export interface Textarea {
  field: string;
}

export interface Url {
  field: string;
}

