import type {
  CapabilityName,
  CollectionDefinition,
  ResolvedCapabilities,
} from "@blazing-cms/types";

import {
  TypeGenerator,
  ValidationGenerator,
  SdkGenerator,
  GenerationPipeline,
} from "@blazing-cms/generators";
import { SchemaLoader, type SchemaResult } from "@blazing-cms/schema";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { resolveCapabilities } from "../shared/capabilities.js";
import { hasWorkflow, resolveWorkflow } from "../shared/workflow.js";
import { loadProjectConfig } from "./load-config.js";
export interface GenerateOptions {
  type?: string;
  dir?: string;
  outDir?: string;
  forceReload?: boolean;
}

async function generateSchemaRegistry(
  collections: unknown[],
  globals: unknown[],
  components: unknown[],
  outDir: string,
) {
  const content = `
// Auto-generated by Blazing CMS — do not edit
import type { CollectionDefinition, GlobalDefinition, ComponentDefinition } from "@blazing-cms/types";

export const collections: CollectionDefinition[] = ${JSON.stringify(collections, null, 2)};
export const globals: GlobalDefinition[] = ${JSON.stringify(globals, null, 2)};
export const components: ComponentDefinition[] = ${JSON.stringify(components, null, 2)};

export function getCollection(slug: string): CollectionDefinition | undefined {
  return collections.find((c) => c.slug === slug);
}
export function getGlobal(slug: string): GlobalDefinition | undefined {
  return globals.find((g) => g.slug === slug);
}
export function getComponent(slug: string): ComponentDefinition | undefined {
  return components.find((c) => c.slug === slug);
}
`;
  writeFileSync(resolve(outDir, "schema-registry.ts"), content.trimStart());
  console.warn(`  ✓ Generated schema-registry.ts`);
}

async function generateAppConfig(outDir: string, resolved: ResolvedCapabilities) {
  const { projectName } = await loadProjectConfig();
  const content = `
// Auto-generated by Blazing CMS — do not edit
export const projectName = ${JSON.stringify(projectName)};
export const capabilities: import("@blazing-cms/types").ResolvedCapabilities = ${JSON.stringify(
    resolved,
    null,
    2,
  )};
`;
  writeFileSync(resolve(outDir, "app-config.ts"), content.trimStart());
  console.warn(`  ✓ Generated app-config.ts`);
}

function collectionGrant(slug: string, action: string): string {
  return `hasGrant("collections:${slug}:${action}") || hasGrant("collections:*:${action}")`;
}

function pascalName(slug: string): string {
  const cleaned = slug.replace(/[^a-zA-Z0-9]/g, "");
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

function workflowCreateCondition(c: CollectionDefinition): string {
  const state = resolveWorkflow(c).defaultState;
  return `(${collectionGrant(c.slug, "create")}) && (request.resource.data.workflowState == null || request.resource.data.workflowState == "${state}")`;
}

function workflowFunction(c: CollectionDefinition): string | null {
  if (!hasWorkflow(c)) return null;
  const resolved = resolveWorkflow(c);
  const pairs = resolved.transitions.map(
    (t) =>
      `(resource.data.workflowState == "${t.from}" && request.resource.data.workflowState == "${t.to}")`,
  );
  const changes = pairs.length > 0 ? ` || ${pairs.join(" || ")}` : "";
  return [
    `    function valid${pascalName(c.slug)}Workflow() {`,
    `      return request.resource.data.workflowState == resource.data.workflowState${changes};`,
    `    }`,
  ].join("\n");
}

function collectionFeature(
  resolved: ResolvedCapabilities,
  slug: string,
  name: CapabilityName,
): boolean {
  return resolved.collections[slug]?.[name] ?? resolved.features[name];
}

function collectionRule(c: CollectionDefinition, resolved: ResolvedCapabilities): string {
  const workflowEnabled = collectionFeature(resolved, c.slug, "workflow");
  const versioningEnabled = collectionFeature(resolved, c.slug, "versioning");
  const lines = [`    match /collections_${c.slug}/{doc} {`];
  if (workflowEnabled && hasWorkflow(c)) {
    lines.push(`      allow create: if ${workflowCreateCondition(c)};`);
  } else {
    lines.push(`      allow create: if ${collectionGrant(c.slug, "create")};`);
  }
  lines.push(`      allow read: if ${collectionGrant(c.slug, "read")};`);
  if (workflowEnabled && hasWorkflow(c)) {
    lines.push(
      `      allow update: if (${collectionGrant(c.slug, "update")}) && valid${pascalName(c.slug)}Workflow();`,
    );
  } else {
    lines.push(`      allow update: if ${collectionGrant(c.slug, "update")};`);
  }
  lines.push(`      allow delete: if ${collectionGrant(c.slug, "delete")};`);
  lines.push(`    }`);
  if (versioningEnabled) {
    lines.push(`    match /collections_${c.slug}/{doc}/versions/{version} {`);
    lines.push(`      allow read: if ${collectionGrant(c.slug, "read")};`);
    lines.push(`      allow create, update, delete: if ${collectionGrant(c.slug, "update")};`);
    lines.push(`    }`);
  }
  return lines.join("\n");
}

function globalRule(g: { slug: string }, resolved: ResolvedCapabilities): string {
  const versioningEnabled = resolved.globals[g.slug]?.versioning ?? resolved.features.versioning;
  const lines = [
    `    match /globals_${g.slug}/{doc} {`,
    `      allow read, write: if hasSystem("manageSettings");`,
    `    }`,
  ];
  if (versioningEnabled) {
    lines.push(
      `    match /globals_${g.slug}/value/versions/{version} {`,
      `      allow read, write: if hasSystem("manageSettings");`,
      `    }`,
    );
  }
  return lines.join("\n");
}

const RBAC_HELPER_RULES = [
  `    // RBAC helpers`,
  `    function isSignedIn() {`,
  `      return request.auth != null;`,
  `    }`,
  `    function userGrants() {`,
  `      return get(/databases/$(database)/documents/collections_user_roles/$(request.auth.uid)).data.grants;`,
  `    }`,
  `    function hasGrant(grant) {`,
  `      return isSignedIn() && (grant in userGrants() || ("*:*" in userGrants()));`,
  `    }`,
  `    function hasSystem(flag) {`,
  `      return hasGrant("system:" + flag);`,
  `    }`,
].join("\n");

const RBAC_RULES = [
  `    // RBAC platform collections`,
  `    match /collections_roles/{doc} {`,
  `      allow read, create, update, delete: if hasSystem("manageRoles");`,
  `    }`,
  `    match /collections_users/{doc} {`,
  `      allow read, create, update, delete: if hasSystem("manageUsers");`,
  `    }`,
  `    match /collections_user_roles/{doc} {`,
  `      allow read: if hasSystem("manageUsers") || hasSystem("manageRoles");`,
  `      allow create, update: if hasSystem("manageUsers") || hasSystem("manageRoles") || (isSignedIn() && request.resource.data.userId == request.auth.uid && request.resource.data.roleIds.size() == 0);`,
  `      allow delete: if hasSystem("manageUsers") || hasSystem("manageRoles");`,
  `    }`,
  `    match /collections_access_logs/{doc} {`,
  `      allow create: if isSignedIn();`,
  `      allow read: if hasSystem("manageUsers");`,
  `      allow update, delete: if false;`,
  `    }`,
].join("\n");

const MEDIA_RULES = [
  `    // Media`,
  `    match /media/{doc} {`,
  `      allow read, create, update, delete: if hasSystem("manageMedia");`,
  `    }`,
].join("\n");

const NOTIFICATIONS_RULES = [
  `    // Notifications`,
  `    match /notifications/{doc} {`,
  `      allow create: if isSignedIn();`,
  `      allow read: if isSignedIn() && resource.data.userId == request.auth.uid;`,
  `      allow update: if isSignedIn() && request.resource.data.userId == request.auth.uid;`,
  `      allow delete: if hasSystem("manageUsers");`,
  `    }`,
].join("\n");

async function generateFirestoreRules(
  collections: CollectionDefinition[],
  globals: { slug: string }[],
  resolved: ResolvedCapabilities,
) {
  const contentEnabled = resolved.features.content;
  const workflowFunctions = collections
    .filter((c) => contentEnabled && collectionFeature(resolved, c.slug, "workflow"))
    .map(workflowFunction)
    .filter((fn): fn is string => fn !== null);

  const collectionRules = contentEnabled ? collections.map((c) => collectionRule(c, resolved)) : [];
  const globalRules = contentEnabled ? globals.map((g) => globalRule(g, resolved)) : [];

  const sections: string[] = [];
  sections.push(RBAC_HELPER_RULES);
  if (workflowFunctions.length > 0) {
    sections.push(`    // Workflow transition helpers\n${workflowFunctions.join("\n")}`);
  }
  if (collectionRules.length > 0) {
    sections.push(`    // Per-collection content rules\n${collectionRules.join("\n")}`);
  }
  if (globalRules.length > 0) {
    sections.push(`    // Global content rules\n${globalRules.join("\n")}`);
  }
  if (resolved.features.rbac) {
    sections.push(RBAC_RULES);
  }
  if (resolved.features.media) {
    sections.push(MEDIA_RULES);
  }
  if (resolved.features.notifications) {
    sections.push(NOTIFICATIONS_RULES);
  }

  const rules = `
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

${sections.join("\n\n")}

    // Deny everything else
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;
  writeFileSync(resolve(process.cwd(), "firestore.rules"), rules.trimStart());
  console.warn(`  ✓ Generated firestore.rules`);
}

async function generateFirestoreIndexes(_collections: unknown[]) {
  const indexes = {
    indexes: [] as unknown[],
  };
  writeFileSync(resolve(process.cwd(), "firestore.indexes.json"), JSON.stringify(indexes, null, 2));
  console.warn(`  ✓ Generated firestore.indexes.json`);
}

const _dirname = fileURLToPath(new URL(".", import.meta.url));
const ADMIN_ROOT = resolve(_dirname, "../../src/admin");

function shouldRun(type: string | undefined, kind: string): boolean {
  return type === undefined || type === kind;
}

function schemaDirFor(options: GenerateOptions): string {
  return resolve(process.cwd(), options.dir ?? "cms");
}

function outDirFor(options: GenerateOptions): string {
  return options.outDir
    ? resolve(process.cwd(), options.outDir)
    : resolve(ADMIN_ROOT, "__generated__");
}

async function addBaseGenerators(options: GenerateOptions, pipeline: GenerationPipeline) {
  if (shouldRun(options.type, "types")) pipeline.addGenerator(new TypeGenerator());
  if (shouldRun(options.type, "validation")) pipeline.addGenerator(new ValidationGenerator());
  if (shouldRun(options.type, "sdk")) pipeline.addGenerator(new SdkGenerator());
}

async function runExtras(
  options: GenerateOptions,
  schema: SchemaResult,
  outDir: string,
  resolved: ResolvedCapabilities,
) {
  if (shouldRun(options.type, "registry")) {
    await generateSchemaRegistry(schema.collections, schema.globals, schema.components, outDir);
    await generateAppConfig(outDir, resolved);
  }
  if (shouldRun(options.type, "rules")) {
    await generateFirestoreRules(schema.collections, schema.globals, resolved);
  }
  if (shouldRun(options.type, "indexes")) {
    await generateFirestoreIndexes(schema.collections);
  }
}

export async function generate(options: GenerateOptions): Promise<void> {
  const schemaDir = schemaDirFor(options);
  const outDir = outDirFor(options);

  if (!existsSync(schemaDir)) {
    console.warn(`  ⚠ Schema directory not found: ${schemaDir}`);
    console.warn("  Skipping code generation.\n");
    return;
  }

  console.warn(`  Loading schemas from ${schemaDir}...`);
  const loader = new SchemaLoader(schemaDir, options.forceReload);
  const schema = await loader.load();

  console.warn(
    `  Found ${schema.collections.length} collections, ${schema.globals.length} globals\n`,
  );

  const { capabilities } = await loadProjectConfig();
  const resolved = resolveCapabilities(capabilities, schema.collections, schema.globals);

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const pipeline = new GenerationPipeline();
  await addBaseGenerators(options, pipeline);
  await runExtras(options, schema, outDir, resolved);
  await pipeline.run(schema.collections, schema.globals, schema.components, outDir);

  if (!options.type) {
    console.warn(`\n  Generated files in ${outDir}`);
  }
}
